### ISSUE TITLE
Credentials are ignored

### ISSUE THREAD

**Issue by rabejens** [gilcloud/sbt-gitlab#29]
I set up a new Gitlab token with `api` access, then I created `~/.sbt/.gitlab.credentials` like so:

```
realm=mygroup
host=my.company.com
user=Private-Token
password=REDACTED
```

In my `build.sbt` I have:

```scala
ThisBuild / useCoursier := false

credentials += Credentials(Path.userHome / ".sbt" / ".gitlab.credentials")
resolvers += "mygroup" at "https://my.company.com/api/v4/groups/420/-/packages/maven"
```

Now,

```scala
libraryDependencies += "com.company.my" %% "my-lib" % "1.2.3"
```

But it still can't find the package. It seems to ignore the credentials:

```
[warn] 	module not found: com.company.my#my-lib_2.12;1.2.3
[warn] ==== local: tried
[warn]   C:\Users\MyUsername\.ivy2\local\com.company.my\my-lib_2.12\1.2.3\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/company/my/my-lib_2.12/1.2.3/my-lib_2.12-1.2.3.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\MyUsername\.sbt\preloaded\com.company.my\my-lib_2.12\1.2.3\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/MyUsername/.sbt/preloaded/com/company/my/my-lib_2.12/1.2.3/my-lib_2.12-1.2.3.pom
[warn] ==== mygroup: tried
[warn]   https://my.company.com/api/v4/groups/420/-/packages/maven/com/company/my/my-lib_2.12/1.2.3/my-lib_2.12-1.2.3.pom
```

When I follow the link and log in to our company Gitlab previously, the POM is downloaded fine.

What is going wrong here? What am I missing?

When I set up a Maven project accessing this repo, everything works fine.

**Comment by rabejens** [comment]
At least this is something I can work with. Since SBT uses regular Scala code, I can put my credentials file anywhere and just look for the file.

Version 0.1.2, btw., even crashes on me when running locally:

```
Extracting structure failed, reason: structure file is empty
stack trace is suppressed; run 'last headerAuthHandler' for the full output
stack trace is suppressed; run 'last ssExtractDependencies' for the full output
(headerAuthHandler) java.util.NoSuchElementException: None.get
(ssExtractDependencies) java.util.NoSuchElementException: None.get
Total time: 0 s, completed Nov 25, 2022 12:13:29 PM
```

```
last headerAuthHandler
[error] java.util.NoSuchElementException: None.get
[error]         at scala.None$.get(Option.scala:529)
[error]         at scala.None$.get(Option.scala:527)
[error]         at com.gilcloud.sbt.gitlab.GitlabPlugin$.$anonfun$gitLabProjectSettings$12(GitlabPlugin.scala:72)
[error]         at com.gilcloud.sbt.gitlab.GitlabPlugin$.$anonfun$gitLabProjectSettings$12$adapted(GitlabPlugin.scala:61)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:750)
[error] (headerAuthHandler) java.util.NoSuchElementException: None.get
```

**Comment by Magnie** [comment]
I am running into the same issue at my company. I've tried the credentials file, I've tried putting the key directly into the code, different realms (`gitlab` and `gitlab-maven`), and they all end with "not found" errors.

**Comment by rabejens** [comment]
This really seems to be an Ivy issue, because when trying to get dependencies on the fly from within Apache Spark, I am hitting the same problems.

**Comment by hoop33** [comment]
I just hit this issue after upgrading from sbt 1.6.2 to 1.8.2. I checked the sbt manual, and everything looked the same for specifying credentials. On a whim, I tried:

`ThisBuild / credentials += ...`

instead of:

`credentials += ...`

And that worked. YMMV.
